### ISSUE TITLE
Chart is incomplete

### ISSUE THREAD

**Issue by abw333** [cedricdelpoux/react-svg-piechart#21] opened 2018-06-09 03:26 UTC
I am using version 2.1.0.

This is my code:
```
<ReactSvgPieChart data={[{"title":"a","value":0.3,"color":"#123456"},{"title":"b","value":0.4,"color":"#654321"}]} />
```

And this is the result:
<img width="256" src="https://user-images.githubusercontent.com/1274347/41187165-b83c8622-6b71-11e8-8d76-fe7dc30d9ee3.png">

It seems that this happens when there is more than one section and at least one of the values is less than 1.

**Comment by cedricdelpoux** [comment] 2018-06-13 10:13
Hi @abw333, thank you for reporting this. With you data I could reproduce. So I publish a new version. Please checkout the v2.1.1.

I close the issue. Feel free to reopen it if the problem is still there.

Thank you

**Closed as completed by cedricdelpoux** 2018-06-13 10:13 UTC

**Comment by abw333** [comment] 2018-06-13 12:28
The issue is fixed - thank you!
